spring.application.name=cypher
spring.datasource.url=jdbc:postgresql://localhost:5432/cypher
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keystore configuration
cypher.jwt.keystore.location=file:secrets/cypher-keystore.p12
cypher.jwt.keystore.password=${KEYSTORE_PASSWORD}
cypher.jwt.keystore.alias=cypher-key
